### ISSUE TITLE
Get empty array from disba

### ISSUE THREAD

**Issue by xichaoqiang** [keurfonluu/disba#20]
**Description of the problem**

I want simulate some muliti-mode phase-velocity dispersion of near surface layer model.

The target frequency range is [1,100]Hz.Only the fundament dispersion curve can be compated. The first and second modes are empty.

When I change the frequency range to [10,100]Hz，the compuation will not stop.

When I change the frequency range to  [20,100]Hz，I can get three modes dispersion curves.

**Full code that generated the error**

```python
import numpy

from disba import PhaseDispersion

# Velocity model and periods
velocity_model = numpy.array(
    [
        [0.002,0.65,0.194,1.82],
        [0.003,0.75,0.270,1.86],
        [0.004,1.40,0.367,1.91],
        [0.005,1.80,0.485,1.96],
        [0.006,2.15,0.603,2.02],
        [10.00,2.80,0.740,2.09],
    ]
)
freq = numpy.linspace(1.0, 100.0, 50.0)

# Dispersion curve
pd = PhaseDispersion(*velocity_model.T)
labels = {
    0: "Fundamental",
    1: "Mode 1",
    2: "Mode 2",
}
cpss=list()
for wave in ["rayleigh"]:
#    fig = plt.figure()

    for i in range(3):
        cp = pd(1./freq, mode=i, wave=wave)
        cpss.append(cp)
```

**Full error message**

```
PASTE ERROR MESSAGE HERE
```

**System information**

* Operating system:Windows 10
* Python installation (Anaconda, system, ETS):Anaconda
* Version of Python:3.7.4
* Version of this package:0.4.0

**Comment by keurfonluu** [comment]
Hi @xichaoqiang,

Sorry for the delay, I have been quite busy this week.

`disba` works with period axis that must be sorted in increasing order. Thus you have to revert the frequency axis too (i.e. `period = 1.0 / freq[::-1]`).

```python
import numpy

from disba import PhaseDispersion
import matplotlib.pyplot as plt

velocity_model = numpy.array(
    [
        [0.002, 0.65, 0.194, 1.82],
        [0.003, 0.75, 0.270, 1.86],
        [0.004, 1.40, 0.367, 1.91],
        [0.005, 1.80, 0.485, 1.96],
        [0.006, 2.15, 0.603, 2.02],
        [10.00, 2.80, 0.740, 2.09],
    ]
)
pd = PhaseDispersion(*velocity_model.T)

freq = numpy.linspace(1.0, 100.0, 100)
period = 1.0 / freq[::-1]

fig, ax = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
for i in range(3):
    cp = pd(period, mode=i, wave="rayleigh")

    ax[0].semilogx(cp.period, cp.velocity)
    ax[0].set_xlabel("Period (s)")

    ax[1].plot(1.0 / cp.period[::-1], cp.velocity[::-1])
    ax[1].set_xlabel("Frequency (Hz)")

    ax[0].set_ylabel("Phase velocity (km/s)")

fig.tight_layout()
```

![sample](https://user-images.githubusercontent.com/16566206/104857755-86531b00-58cf-11eb-978c-8b8c4db96295.png)

Note that I have fixed the infinite loop for Mode 2, so please upgrade `disba` to version `0.4.1`: `pip install -U disba --user`.

**Comment by xichaoqiang** [comment]
Thanks for your reply.Your modfication works.

However,I found another problem from the below code.

```
import numpy

from disba import PhaseDispersion
import matplotlib.pyplot as plt

velocity_model = numpy.array(
    [
        [0.002,0.65,0.194,1.82], #L5
        [0.003,0.75,0.270,1.86],
        [0.004,1.40,0.367,1.91],
        [0.005,1.80,0.485,1.96],
        [0.006,0.50,0.150,1.80],
        [1.000,2.80,0.740,2.09],
    ]
)
pd = PhaseDispersion(*velocity_model.T)

freq = numpy.linspace(1.0, 100.0, 200)
period = 1.0 / freq[::-1]

fig, ax = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
for i in range(3):
    cp = pd(period, mode=i, wave="rayleigh")

    ax[0].semilogx(cp.period, cp.velocity)
    ax[0].set_xlabel("Period (s)")

    ax[1].plot(1.0 / cp.period[::-1], cp.velocity[::-1])
    ax[1].set_xlabel("Frequency (Hz)")

    ax[0].set_ylabel("Phase velocity (km/s)")

fig.tight_layout()
```
![图片](https://user-images.githubusercontent.com/30900789/104866730-38dfb800-597a-11eb-8898-ee5380816102.png)

The dispersion curves generated by geopsy are shown in the below.
![图片](https://user-images.githubusercontent.com/30900789/104866741-4006c600-597a-11eb-8d82-de089bab605b.png)

**Comment by keurfonluu** [comment]
You can set the parameter `dc` to a smaller value to avoid "modal jumps". This parameter adjusts the stepsize of the root-searching algorithm:

```python
pd = PhaseDispersion(*velocity_model.T, dc=0.0001)
```

![sample](https://user-images.githubusercontent.com/16566206/104867465-c6c58f80-58f5-11eb-8215-50272df817e7.png)

**Comment by xichaoqiang** [comment]
Thank you very much. It works.

**Comment by xichaoqiang** [comment]
Another problem.

When I change the number of frequencies to 200.I get a wrong result.

 `freq = numpy.linspace(1.0, 50.0, 200)`


```
import numpy

from disba import GroupDispersion
import matplotlib.pyplot as plt

velocity_model = numpy.array(
    [
        [0.002,0.65,0.194,1.82], #L5
        [0.003,0.75,0.270,1.86],
        [0.004,1.40,0.367,1.91],
        [0.005,1.80,0.485,1.96],
        [0.006,0.50,0.150,1.80],
        [1.000,2.80,0.740,2.09],
    ]
)
pd = GroupDispersion(*velocity_model.T, dc=0.0001)

freq = numpy.linspace(1.0, 50.0, 200)
period = 1.0 / freq[::-1]

fig, ax = plt.subplots(1, 2, figsize=(10, 4), sharey=True)
for i in range(3):
    cp = pd(period, mode=i, wave="rayleigh")

    ax[0].semilogx(cp.period, cp.velocity)
    ax[0].set_xlabel("Period (s)")

    ax[1].plot(1.0 / cp.period[::-1], cp.velocity[::-1])
    ax[1].set_xlabel("Frequency (Hz)")

    ax[0].set_ylabel("Phase velocity (km/s)")

fig.tight_layout()
```
![图片](https://user-images.githubusercontent.com/30900789/104868769-4d727f00-597f-11eb-8ea1-423700e369d3.png)
 The belown figure is compuated by `freq = numpy.linspace(1.0, 50.0, 100)`
![图片](https://user-images.githubusercontent.com/30900789/104868782-58c5aa80-597f-11eb-9b75-6aa61a38c974.png)

**Comment by xichaoqiang** [comment]
I am trying the PhaseSensitivity function and found that the accuracy of the sensitivity matrix is ​​not high.

I use the model from Xia et al.,1999. 

![图片](https://user-images.githubusercontent.com/30900789/104872957-469d3980-598a-11eb-805c-d7118a82a665.png)

I compute the sensitivity matrix at f (=5, 10, 15,20, 25, and 30 Hz) .

The figure below is the sensitivity matrix from the below code.
```
import numpy
from disba import PhaseSensitivity

velocity_model = numpy.array(
    [
        [0.0020,0.65,0.194,1.82], #(Xia et al.,1999 Table.1 )
        [0.0023,0.75,0.270,1.86],
        [0.0025,1.40,0.367,1.91],
        [0.0028,1.80,0.485,1.96],
        [0.0032,2.15,0.603,2.02],
        [1.0000,2.80,0.740,2.09],
    ]
)
ps = PhaseSensitivity(*velocity_model.T, dc= 0.0001)
labels = {
     "velocity_s": "$\\partial c / \\partial \\beta$",
}

freqs=numpy.r_[5: 35:5] #f (=5, 10, 15,20, 25, and 30 Hz)
sen_mat=numpy.zeros((6,6)) #(Xia et al.,1999 ((2)))
for i in range(0,6):
    sk = ps(1.0/freqs[i], mode=0, wave="rayleigh", parameter="velocity_s")
    sen_mat[i,:]=sk[1]
```
![图片](https://user-images.githubusercontent.com/30900789/104873071-9a0f8780-598a-11eb-8c9c-966b90d93952.png)

The sensitivity matrix of the same model with different algorithm are shown below.

![图片](https://user-images.githubusercontent.com/30900789/104873175-e5299a80-598a-11eb-91c3-d15964af26ad.png)

**Comment by keurfonluu** [comment]
Sensitivity kernels are numerically approximated (finite-difference), this is obviously less accurate than analytical solutions.
You can try adjusting the factor `dp`, but I wouldn't bother much.

**Comment by xichaoqiang** [comment]
Thanks for your reply.

Is there any problem in the depth array.The thinkness of first layer is 0.0020.

![图片](https://user-images.githubusercontent.com/30900789/104877767-89b0da00-5995-11eb-877b-d77c1d989fa9.png)

**Comment by keurfonluu** [comment]
Most `disba` objects have a magic method `__call__` that returns a namedtuple. The first item of the namedtuple returned by a sensitivity kernel object is the depth, not thickness. The depth is returned mainly for plotting purpose.
