### ISSUE TITLE
Citing needed

### ISSUE THREAD

**Issue by h-cas-valle** [keurfonluu/disba#29]
First, it´s great software! 

**Description of the desired feature**

The problem is that I have no formal way to cite it in a publication! Please if you have a paper to reference about this package add it to the description/manual/wiki so the community can cite it. If not, you should publish your results!! Mainly becouse  it's awesome for scientits that work on python.

Congrats for the soft!

**Are you willing to help implement and maintain this feature?** Yes/No

**Comment by keurfonluu** [comment]
Hi @h-cas-valle ,

Thanks for your interest!
I've just added a citation file that shows how you can cite this work (see Citation in About section of the homepage):

![citation](https://user-images.githubusercontent.com/16566206/135666117-3f4a83b8-f47d-48a1-907d-966bff8e4922.png)

**Comment by hcasvalle** [comment]
Yes! Saw it, I turned on notif for this package.

I cited you on my thesis!

Thank you very much!
