### ISSUE TITLE
Sensitivity kernel examples in Matplotlib

### ISSUE THREAD

**Issue by suhsane** [keurfonluu/disba#35]
Hi, thank you for creating this code. I found it very straightforward to install.

I am running into issues with reproducing the example plots that are shown in the example. I can recreate the dispersion curves and normalized eigenfunction plots using Matplotlib within a Jupyter Notebook (see attached pdf containing Jupyter notebook code and outputs). However, when I attempt to recreate the sensitivity kernels and ellipticity outputs, my results do not appear similar to the tutorial (see attached image comparing Rayleigh-wave sensitivity kernels). I'm not sure if this is due to the type of plotting used, or if there is another issue within my implementation of the code. Thank you in advance for your support with this.

![image](https://user-images.githubusercontent.com/6075834/142010576-fbeca68c-1b6f-49b9-80ad-47edaae6c0c3.png)

[disba_example.pdf](https://github.com/keurfonluu/disba/files/7547481/disba_example.pdf)

**Comment by keurfonluu** [comment]
Hi @suhsane ,

You can find the script that generated the figures in [`.github`](https://github.com/keurfonluu/disba/blob/master/.github/sample.py) folder.
Looking at your sensitivity plots, it seems that you did not use the method `resample`.

However, the dispersion curve of your fundamental mode seems to indicate that you are using the fast-delta algorithm by default, which means that your `disba` is outdated. By default, `disba` is now using the Dunkin's matrix algorithm as CPS and Geopsy. Please update `disba`: `pip install disba -U`.

I am not sure why the fast-delta algorithm behaves differently for some periods, though.

**Comment by suhsane** [comment]
Hi @keurfonluu - thank you so much for your prompt response. I updated disba as you suggested, and then applied your sample code within a Jupyter Notebook. I can confirm that I am now getting the same outputs as shown in your example. Thanks very much for your help with this.
