### ISSUE TITLE
Dunkin matrix method can find the root while the fast-delta matrix method can't (base order)

### ISSUE THREAD

**Issue by liufeng2317** [keurfonluu/disba#38]
**Description of the problem**

I set a two layer model :
```
model.true_model
```
{'thick': [0.002, 0.015],
 'vp': [1.2375343056249999, 1.740763080625],
 'vs': [0.15, 0.45],
 'rho': [1.4501699956971361, 1.7773312121113325]
}

and then  I use the dunkin matrix method and fast-delta method to calcualte the dispersion wave,I get a two different result following:
```python
from disba import PhaseDispersion
Velocity_model = np.hstack((thick_true.reshape(-1,1),vp.reshape(-1,1),vs.reshape(-1,1),rho.reshape(-1,1)))
t = np.linspace(1/60,1/5,100)
pd = PhaseDispersion(*Velocity_model.T,algorithm="dunkin")
cpr = [pd(t, mode=i, wave="rayleigh") for i in range(3)]
cpr
```
![image](https://user-images.githubusercontent.com/53359225/191014205-4b5e9449-2403-4209-b481-711752bdd247.png)

```python
from disba import PhaseDispersion
Velocity_model = np.hstack((thick_true.reshape(-1,1),vp.reshape(-1,1),vs.reshape(-1,1),rho.reshape(-1,1)))
t = np.linspace(1/60,1/5,100)
pd = PhaseDispersion(*Velocity_model.T,algorithm="fast-delta")
cpr = [pd(t, mode=i, wave="rayleigh") for i in range(3)]
cpr
```
![image](https://user-images.githubusercontent.com/53359225/191014340-27e1db2c-7f2f-43e1-b369-582646672974.png)

**System information**

* Operating system: Ubuntu
* Python installation (Anaconda, system, ETS):Anaconda python3.8
* Version of Python:python 3.8
* Version of this package:

**Comment by keurfonluu** [comment]
Indeed, these two algorithms calculate the secular function differently. For some models, Dunkin's matrix algorithm works but Fast Delta doesn't, for others, it's the opposite. However, I would recommend using Dunkin's matrix for most cases and only try Fast Delta if Dunkin's matrix fails.
