### ISSUE TITLE
Updating for Numpy > v2.0

### ISSUE THREAD

**Issue by mdenolle** [keurfonluu/disba#43]
Hello! Thank you for such an amazing piece of code!
There is a quick update that would be great for future usage since Numpy migrated to v2+

**Full code that generated the error**

https://github.com/Denolle-Lab/surface_wave_sensitivity/blob/main/SensKernels/sensitivity_GJI.ipynb

I just pip installed ``disba`` with a recent numpy (v2.0.1) and got the following error:

``AttributeError: `np.complex_` was removed in the NumPy 2.0 release. Use `np.complex128` instead.``

Will use a older version of numpy for now but a quick fix might be to change this in the two lines:
https://github.com/search?q=repo%3Akeurfonluu%2Fdisba%20np.complex_&type=code

You may be quicker at doing this than me.

Cheers,
Marine

**Comment by keurfonluu** [comment]
Hi @mdenolle,

Thanks for reporting the issue. You can install the updated version from PyPI: ``pip install disba -U``.

**Comment by mdenolle** [comment]
Super quick! Thank you so much
